[build]
builder = "maven"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[build.environment]
JAVA_VERSION = "17"

[deploy.environment]
SPRING_PROFILES_ACTIVE = "prod"